<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHwzGN6A\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHwzGN6A/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHwzGN6A.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHwzGN6A\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHwzGN6A\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HwzGN6A',
    'container.build_id' => '46df52c2',
    'container.build_time' => 1551896533,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHwzGN6A');
